apiVersion: v1
kind: Pod
metadata:
 name: apache-pod
 labels:
  app: apache
spec: 
  containers:
    - name: apache
      image: httpd:latest
  tolerations:
    - key: "app"
      operators: "Equal"
      value: "blue"
      effect: "NoSchedule"   